AllCops:
  TargetRubyVersion: 2.6.5
  Include:
    - rubocop-rails

Metrics/LineLength:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/EndAlignment:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/ElseAlignment:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
