version: "3"
services:
  server: &app_base
    build: .
    command: rails server -p 3001 -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
  data:
    image: busybox
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./bundle:/usr/local/bundle
volumes:
  mysql-data:
    driver: local
  bundle:
    driver: local
